language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn zip
deploy:
  provider: releases
  api_key: 
    secure: "bL4xLRpa7UmtmYphyuZUdtd5armWpuJL75Mz0GZwtXFXhkf2MFhgk57vB/NWdn2hFVS9Tzq1TfiVhKNnc4V4jYXvxdO+sWE0sITsb+8Z6U3cIBAKKHiz+2U/fo8uuYWsTBlrvlclc52H4jTNMfS6vEKM/U3lYyJUOISSLrDuY0EvqMAAo4nNtqu5MPzpa1MI/fLfpns/w8fmpHEUOFdTb8IR60nUHb9r1yoA5l+7vD7dzTWpMvvLKBqyEaIASdvgnjBfPlmN9GY1qxdfCiIc0xpdWQ3uO2p6qvJVsHP5bkjZGlm8C6EjmKsVCgUy6BG0HUmVwtDTA13TJKIw6GwwLuG1ZDyYQDjoaKnEwGM7yVTWbIZjd05zxvYifT5YLWGAqjrGvlh68jnmlzArJWnKzuUNoGAQD8ZBNThn5C3mjVsRqCvf3Bd/vc42QBBnawm+GaVJnQtvu79F3CeIJ2e4R1NZnvo+acNtgqHkCYjreTShMY/I/cc4vTf7aHC9NLS9Q0wMnRlE1ZPmXlN7gESGkPLEim17AfHhHUk1DjhdeTEVAuPYiHF3RBQp/uTBLTyYWUzv7ztv/eiCqrcQzzbHh0VG553ito6rld3rRY7pxffmdOp4nf7YPG8ctr0TUUyhgCezAKaKB1DNSK592s9muDos+AdyRzWYTFKafwoNmNg="
  file: "dist/cozy.zip"
  skip_cleanup: true
  on:
    tags: true
